config/routes.rb
Rails.application.routes.draw do
  namespace :authors do
    get "books/index"
  end
  devise_for :authors

  get "up" => "rails/health#show", as: :rails_health_check
  # root to: proc { [200, {}, ['Hello world']] }

  # Authors CRUD (already present)
  get    "/authors",          to: "authors#index",   as: "authors"
  get    "/authors/new",      to: "authors#new",     as: "new_author"
  post   "/authors",          to: "authors#create"
  get    "/authors/:id",      to: "authors#show",    as: "author"
  get    "/authors/:id/edit", to: "authors#edit",    as: "edit_author"
  patch  "/authors/:id",      to: "authors#update"
  put    "/authors/:id",      to: "authors#update"
  delete "/authors/:id",      to: "authors#destroy"
  get "/about-authors", to: "authors#about", as: "about_authors"

get "/all_books", to: "books#all_books"


  # ✅ "My Books" (only books belonging to the logged-in author)
  resources :authors, only: [] do
    resources :books, only: [:index], controller: "authors/books", as: "my_books"
  end

  # Root after login
  root to: "books#index"

  resources :books do
    member do
      get :about
    end
    resources :comments, only: [:create, :destroy, :edit, :destroy]
    resources :chapters
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable, :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy
         has_many :comments
         has_many :chapters, dependent: :destroy
end

app/controllers/authors/books_controller.rb
class Authors::BooksController < ApplicationController
  before_action :authenticate_author!

  def index
    @page = (params[:page] || 1).to_i
    @per_page = 6
    books_scope = current_author.books
    @total_pages = (books_scope.count / @per_page.to_f).ceil
    @books = books_scope.offset((@page - 1) * @per_page).limit(@per_page)
    render "books/index"
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :set_author, only: [:show, :edit, :update, :destroy]

    def index
        @authors =Author.all 
    end

    def show
    end

    def new
        @author = Author.new 
    end

    
  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to @author, notice: "Author created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit 
  end

  def update 
    if @author.update(author_params)
        redirect_to @author, notice: "Author updated successfully"
    else
    ender :edit, status: :unprocessable_entity
    end 
  end

  def destroy 
    @author.destroy 
    redirect_to authors_path, notice: "Author deleted successfully"
  end

  private

  def set_author 
    @author = Author.find(params[:id])
  end

  def author_params 
    params.require(:author).permit(:name, :bio)
  end
end

app/helpers/authors/books_helper.rb
module Authors::BooksHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<div class="form-container">
  <%= form_with(model: author, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-input" %>
    </div>

    <div class="form-group">
      <%= form.label :bio, class: "form-label" %>
      <%= form.text_area :bio, class: "form-input" %>
    </div>

    <%= form.submit "Save Author", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/authors/edit.html.erb
<h1 class="page-title">Edit Author</h1>
<%= render "form", author: @author %>
<%= link_to "⬅ Back", authors_path, class: "btn btn-secondary" %>

app/views/authors/index.html.erb
<h1 class="page-title">Authors List</h1>

<div class="actions">
  <%= link_to "➕ New Author", new_author_path, class: "btn btn-primary" %>
</div>

<ul class="author-list">
  <% @authors.each do |author| %>
    <li class="author-card">
      <h3><%= author.name %></h3>
      <p><%= truncate(author.bio, length: 80) %></p>

      <div class="author-actions">
        <%= link_to "Show", author_path(author), class: "btn btn-secondary" %>
        <%= link_to "Edit", edit_author_path(author), class: "btn btn-warning" %>
        <%= button_to "Delete", author_path(author),
          method: :delete,
          data: { turbo_confirm: "Are you sure?" },
          class: "btn btn-danger" %>
      </div>
    </li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<h1 class="page-title">New Author</h1>
<%= render "form", author: @author %>
<%= link_to "⬅ Back", authors_path, class: "btn btn-secondary" %>

app/views/authors/show.html.erb
<div class="author-show">
  <h1><%= @author.name %></h1>
  <p><%= @author.bio %></p>

  <div class="author-actions">
    <%= link_to "⬅ Back", authors_path, class: "btn btn-secondary" %>
    <%= link_to "✏ Edit", edit_author_path(@author), class: "btn btn-warning" %>
  </div>
</div>